### ISSUE TITLE
Angular 18 compatibility

### ISSUE THREAD

**Issue by simon-weiler-syzygy** [brakmic/ngx-perfect-scrollbar-portable#1]
Hi there,

as far as I can tell there is currently no compatibility with Angular v18. Is this planned?

Thanks :)
Simon

**Comment by brakmic** [comment]
> Hi there,
> 
> as far as I can tell there is currently no compatibility with Angular v18. Is this planned?
> 
> Thanks :) Simon

Hi Simon,

I haven't tested it yet with Angular 18, but I can try it out and deliver a new version that is compatible with v18. I'll keep you updated on the progress.

Thanks for your patience!

Best,
Harris

**Comment by brakmic** [comment]
Hi Simon,

The new version is now available: [ngx-perfect-scrollbar-portable v10.1.11](https://www.npmjs.com/package/ngx-perfect-scrollbar-portable/v/10.1.11).

Please test it and let me know if you encounter any issues.

Best regards,  
Harris

**Comment by simon-weiler-syzygy** [comment]
Hi Harris,

you are amazing, 1hr between issue and new version is crazy :D

Thank you a lot for your support,
Simon
