### ISSUE TITLE
Angular 19 compatibility

### ISSUE THREAD

**Issue by simon-weiler-syzygy** [brakmic/ngx-perfect-scrollbar-portable#2]
Hi Harris,

We have the same issue as last time again, now with Angular 19. Would you be so kind to change the dependencies for Angular 19?

Thank you :)
Simon

**Comment by brakmic** [comment]
@simon-weiler-syzygy 

Ah yes, Friday code changes because who doesn’t love living on the edge before the weekend? 😉

**Comment by simon-weiler-syzygy** [comment]
Good morning and thank you for your very quick response to this :)

I think there is still one issue left, in projects/lib/package.json there is still a peer dependency to Angular 18. Could you fix this as well?

Thanks a lot :)
Simon

**Comment by brakmic** [comment]
> Good morning and thank you for your very quick response to this :)
> 
> I think there is still one issue left, in projects/lib/package.json there is still a peer dependency to Angular 18. Could you fix this as well?
> 
> Thanks a lot :) Simon

Good morning,

Thanks for the hint. I've fixed it now, and the new version is out.

Regards,

**Comment by simon-weiler-syzygy** [comment]
Awesome :) Thank you and have a great start to the week.
